Tickets/dm 14365
lsst/dax_metaserv pull request #19
Opened 2018-05-18 00:12 UTC by kennywlo

2018-05-21 21:59 UTC, brianv0 requested changes

2018-05-21 21:59 UTC, brianv0 commented on bin/server.py
> +from lsst.dax.metaserv import metaREST_v1
Will you keep the original name?

2018-05-21 21:59 UTC, brianv0 commented on python/lsst/dax/metaserv/metaREST_v1.py
> +        template_folder="templates")
Please keep the original name. Also, the aligning of the second line isn't pep8

2018-05-22 00:18 UTC, kennywlo commented on bin/server.py
> +from lsst.dax.metaserv import metaREST_v1
Will revert.

2018-05-22 00:18 UTC, kennywlo commented on python/lsst/dax/metaserv/metaREST_v1.py
> +        template_folder="templates")
will revert.

2018-05-23 16:04 UTC, merged